/*
 * SPDX-License-Identifier: CC0-1.0
 *
 * CamBrowser network bring-up: on-board IP101 PHY on the ESP32-P4 internal
 * EMAC (RMII) -> esp_eth -> esp_netif -> DHCP, with a tiny status API for
 * the on-screen status bar.
 *
 * Board JC1060P470C_I_W_Y (schematic 5-Schematic/JC1060P470C_I_W_Y-V1.0.pdf):
 * there is NO W5500 on this board. Wired Ethernet is an IC+ IP101 PHY wired
 * straight to the ESP32-P4 EMAC through RMII:
 *   data pins (fixed by the P4 IO-MUX, equal to ETH_ESP32_EMAC_DEFAULT_CONFIG
 *   defaults): TX_EN=49 TXD0=34 TXD1=35 CRS_DV=28 RXD0=29 RXD1=30
 *   REF_CLK: 50 MHz INPUT on GPIO50 - generated by the IP101 from its own
 *   25 MHz crystal, so the EMAC must run in EMAC_CLK_EXT_IN mode.
 *   MDC=31 MDIO=52, PHY reset = GPIO51 (active low), PHY SMI address = 1
 *   (PHY_AD0 is pulled up on the board).
 * SMI/clock/reset/addr come from Kconfig (menu
 * "CamBrowser (Ethernet Browser on LCD)", EB_ETH_* options).
 */

#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_eth.h"
#include "esp_eth_mac_esp.h"        /* eth_esp32_emac_config_t, esp_eth_mac_new_esp32() */
#include "esp_idf_version.h"
#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(6, 0, 0)
/* IDF v6: the IP101 PHY driver moved out of esp_eth into the managed
 * component espressif/ip101 (see main/idf_component.yml). */
#include "esp_eth_phy_ip101.h"
#else
/* IDF 5.x: IP101 is still part of the esp_eth component itself. */
#include "esp_eth_phy.h"
#endif
#include "esp_netif.h"
#include "esp_event.h"
#include "driver/gpio.h"
#include "sdkconfig.h"
#include "net/app_eth.h"

static const char *TAG = "app_eth";

typedef enum {
    ETH_STATE_DOWN = 0,     /* driver not started or cable detached   */
    ETH_STATE_LINK_UP,      /* PHY link detected, waiting for DHCP    */
    ETH_STATE_GOT_IP,       /* DHCP done, network ready               */
} eth_state_t;

static struct {
    esp_eth_handle_t        eth_handle;
    esp_netif_t            *netif;
    volatile eth_state_t    state;
    char                    ip_str[16];
    char                    reason[48];  /* last status line for the UI */
} s_eth;

static void eth_set_state(eth_state_t st, const char *reason)
{
    s_eth.state = st;
    if (reason != NULL) {
        strlcpy(s_eth.reason, reason, sizeof(s_eth.reason));
    }
    ESP_LOGI(TAG, "state=%d (%s)", (int)st, s_eth.reason);
}

static void eth_event_handler(void *arg, esp_event_base_t event_base,
                              int32_t event_id, void *event_data)
{
    switch (event_id) {
    case ETHERNET_EVENT_CONNECTED:
        /* esp_eth_netif_glue starts the DHCP client on this event itself */
        eth_set_state(ETH_STATE_LINK_UP, "link up, dhcp...");
        break;
    case ETHERNET_EVENT_DISCONNECTED:
        eth_set_state(ETH_STATE_DOWN, "cable detached");
        break;
    case ETHERNET_EVENT_START:
        ESP_LOGI(TAG, "eth driver started");
        break;
    case ETHERNET_EVENT_STOP:
        eth_set_state(ETH_STATE_DOWN, "eth stopped");
        break;
    default:
        break;
    }
}

static void ip_event_handler(void *arg, esp_event_base_t event_base,
                             int32_t event_id, void *event_data)
{
    ip_event_got_ip_t *evt = (ip_event_got_ip_t *)event_data;
    const esp_netif_ip_info_t *ip = &evt->ip_info;

    snprintf(s_eth.ip_str, sizeof(s_eth.ip_str), IPSTR, IP2STR(&ip->ip));
    eth_set_state(ETH_STATE_GOT_IP, "got ip");
    ESP_LOGI(TAG, "Got IP: %s, gw " IPSTR, s_eth.ip_str, IP2STR(&ip->gw));
}

esp_err_t app_eth_start(void)
{
    if (s_eth.eth_handle != NULL) {
        return ESP_OK;  /* already started */
    }
    eth_set_state(ETH_STATE_DOWN, "starting...");

    /* Netif + event loop (idempotent for IDF 5.x where the app may not have
     * done this yet; on repeated calls both return ESP_OK/ESP_ERR_INVALID_STATE
     * which we tolerate). */
    esp_err_t err = esp_netif_init();
    if (err != ESP_OK && err != ESP_ERR_INVALID_STATE) {
        ESP_LOGE(TAG, "esp_netif_init: %s", esp_err_to_name(err));
        return err;
    }
    err = esp_event_loop_create_default();
    if (err != ESP_OK && err != ESP_ERR_INVALID_STATE) {
        ESP_LOGE(TAG, "esp_event_loop_create_default: %s", esp_err_to_name(err));
        return err;
    }

    err = esp_event_handler_register(ETH_EVENT, ESP_EVENT_ANY_ID,
                                     eth_event_handler, NULL);
    err |= esp_event_handler_register(IP_EVENT, IP_EVENT_ETH_GOT_IP,
                                      ip_event_handler, NULL);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "event handler registration failed");
        return err;
    }

#if CONFIG_EB_ETH_RST_GPIO >= 0
    /* Defensive hard reset of the IP101 before the first SMI transaction.
     * The driver validates the chip ID (OUI 0x90C3, model 5) during
     * esp_eth_driver_install() BEFORE issuing its own BMCR soft reset, and
     * MDIO does not answer while RSTN is held low - a PHY stuck in reset at
     * boot would fail install with "wrong chip ID". A short active-low
     * pulse makes the bring-up independent of the power-on state of
     * GPIO51. */
    {
        gpio_config_t rst_io = {
            .pin_bit_mask = 1ULL << CONFIG_EB_ETH_RST_GPIO,
            .mode = GPIO_MODE_OUTPUT,
            .intr_type = GPIO_INTR_DISABLE,
        };
        if (gpio_config(&rst_io) == ESP_OK) {
            gpio_set_level(CONFIG_EB_ETH_RST_GPIO, 0);
            vTaskDelay(pdMS_TO_TICKS(20));
            gpio_set_level(CONFIG_EB_ETH_RST_GPIO, 1);
            vTaskDelay(pdMS_TO_TICKS(100));     /* PHY PLL lock after reset deassert */
        }
    }
#endif

    /* Common MAC and PHY configs */
    eth_mac_config_t mac_config = ETH_MAC_DEFAULT_CONFIG();
    eth_phy_config_t phy_config = ETH_PHY_DEFAULT_CONFIG();
    phy_config.phy_addr = CONFIG_EB_ETH_PHY_ADDR;        /* 1: PHY_AD0 pulled up */
    phy_config.reset_gpio_num = CONFIG_EB_ETH_RST_GPIO;  /* 51, active low      */

    /* EMAC-specific config. On ESP32-P4 the defaults already match this
     * board exactly (RMII data pins 49/34/35/28/29/30, clock input on
     * GPIO50, MDC 31 / MDIO 52); SMI and clock are still set explicitly
     * from Kconfig so the mapping stays visible and tunable. */
    eth_esp32_emac_config_t emac_config = ETH_ESP32_EMAC_DEFAULT_CONFIG();
    emac_config.smi_gpio.mdc_num = CONFIG_EB_ETH_MDC_GPIO;
    emac_config.smi_gpio.mdio_num = CONFIG_EB_ETH_MDIO_GPIO;
    /* 50 MHz REF_CLK comes FROM the IP101 into the P4 -> external input
     * mode. EMAC_CLK_OUT would drive the wrong direction and the link
     * would never come up. */
    emac_config.clock_config.rmii.clock_mode = EMAC_CLK_EXT_IN;
    emac_config.clock_config.rmii.clock_gpio = CONFIG_EB_ETH_RMII_CLK_GPIO;

    esp_eth_mac_t *mac = esp_eth_mac_new_esp32(&emac_config, &mac_config);
    esp_eth_phy_t *phy = esp_eth_phy_new_ip101(&phy_config);
    if (mac == NULL || phy == NULL) {
        ESP_LOGE(TAG, "esp_eth_mac_new_esp32/esp_eth_phy_new_ip101 failed");
        return ESP_FAIL;
    }

    esp_eth_config_t eth_config = ETH_DEFAULT_CONFIG(mac, phy);
    if (esp_eth_driver_install(&eth_config, &s_eth.eth_handle) != ESP_OK) {
        ESP_LOGE(TAG, "esp_eth_driver_install failed");
        return ESP_FAIL;
    }

    /* Netif + glue */
    esp_netif_config_t netif_cfg = ESP_NETIF_DEFAULT_ETH();
    s_eth.netif = esp_netif_new(&netif_cfg);
    if (s_eth.netif == NULL) {
        ESP_LOGE(TAG, "esp_netif_new failed");
        return ESP_FAIL;
    }

    esp_eth_netif_glue_handle_t glue = esp_eth_new_netif_glue(s_eth.eth_handle);
    if (glue == NULL || esp_netif_attach(s_eth.netif, glue) != ESP_OK) {
        ESP_LOGE(TAG, "esp_netif_attach failed");
        return ESP_FAIL;
    }

    if (esp_eth_start(s_eth.eth_handle) != ESP_OK) {
        ESP_LOGE(TAG, "esp_eth_start failed");
        return ESP_FAIL;
    }

    ESP_LOGI(TAG, "IP101 started on internal EMAC, RMII (mdc=%d mdio=%d "
             "clk_in=%d rst=%d addr=%d)",
             CONFIG_EB_ETH_MDC_GPIO, CONFIG_EB_ETH_MDIO_GPIO,
             CONFIG_EB_ETH_RMII_CLK_GPIO, CONFIG_EB_ETH_RST_GPIO,
             CONFIG_EB_ETH_PHY_ADDR);
    return ESP_OK;
}

bool app_eth_ready(void)
{
    return s_eth.state == ETH_STATE_GOT_IP;
}

const char *app_eth_ip_str(void)
{
    return s_eth.ip_str;
}

const char *app_eth_status_str(void)
{
    return s_eth.reason;
}

app_eth_state_t app_eth_state(void)
{
    return (app_eth_state_t)s_eth.state;
}
