#ifndef HOST_PSTATS_ESP_PLAYER_TYPES_H
#define HOST_PSTATS_ESP_PLAYER_TYPES_H
typedef enum {
    ESP_PLAYER_EVENT_NONE = 0,
    ESP_PLAYER_EVENT_PLAYED,
    ESP_PLAYER_EVENT_PAUSED,
    ESP_PLAYER_EVENT_STOPPED,
    ESP_PLAYER_EVENT_SEEK_DONE,
    ESP_PLAYER_EVENT_FINISHED,
    ESP_PLAYER_EVENT_BUFFERING,
    ESP_PLAYER_EVENT_BUFFERED,
    ESP_PLAYER_EVENT_ERROR,
    ESP_PLAYER_EVENT_TRACK_INFO_PARSED,
    ESP_PLAYER_EVENT_AUDIO_INFO_PARSED,
    ESP_PLAYER_EVENT_VIDEO_INFO_PARSED,
} esp_player_event_type_t;
#endif
