/*
 * SPDX-License-Identifier: CC0-1.0
 *
 * CamBrowser UI icons: 16x16 1-bit pictograms, AUTO-GENERATED by
 * scripts/gen_icons.py from ASCII art. Do not edit by hand - edit the
 * art in the generator and re-run it. Bit 15 of each word is the
 * LEFTMOST pixel (same layout as the 8x8 font in app_overlay.c).
 *
 */

#ifndef CAMOS_UI_ICONS_H
#define CAMOS_UI_ICONS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define UI_ICON_W 16
#define UI_ICON_H 16

typedef struct ui_icon {
    uint16_t row[UI_ICON_H];
} ui_icon_t;

/* SEARCH */
static const ui_icon_t __attribute__((unused)) ui_icon_search = {
    .row = {
        0x0000,
        0x0780,
        0x0840,
        0x1020,
        0x2010,
        0x2010,
        0x2010,
        0x2010,
        0x1020,
        0x0840,
        0x0798,
        0x0024,
        0x0018,
        0x000C,
        0x0018,
        0x0000,
    }
};

/* GLOBE */
static const ui_icon_t __attribute__((unused)) ui_icon_globe = {
    .row = {
        0x0000,
        0x07E0,
        0x1818,
        0x2184,
        0x4242,
        0x4422,
        0x8421,
        0x8421,
        0x8421,
        0x8421,
        0x4422,
        0x4242,
        0x2184,
        0x1818,
        0x07E0,
        0x0000,
    }
};

/* FILM */
static const ui_icon_t __attribute__((unused)) ui_icon_film = {
    .row = {
        0x0000,
        0x6DB6,
        0x7FFE,
        0x0000,
        0x7BBC,
        0x4224,
        0x4224,
        0x7A1C,
        0x0A78,
        0x4224,
        0x4224,
        0x7BBC,
        0x0000,
        0x6DB6,
        0x7FFE,
        0x0000,
    }
};

/* CLAP */
static const ui_icon_t __attribute__((unused)) ui_icon_clap = {
    .row = {
        0x0000,
        0xFFFF,
        0x5555,
        0xFFFF,
        0x69A6,
        0x8001,
        0x9009,
        0x8001,
        0x8181,
        0x8001,
        0x9009,
        0x8001,
        0xFFFF,
        0x0000,
        0x0000,
        0x0000,
    }
};

/* MUSIC */
static const ui_icon_t __attribute__((unused)) ui_icon_music = {
    .row = {
        0x0000,
        0x00F0,
        0x0088,
        0x0084,
        0x0084,
        0x0084,
        0x0084,
        0x0084,
        0x0C84,
        0x1F04,
        0x1304,
        0x1004,
        0x1804,
        0x0FF8,
        0x0000,
        0x0000,
    }
};

/* PLAY */
static const ui_icon_t __attribute__((unused)) ui_icon_play = {
    .row = {
        0x0000,
        0x0400,
        0x0600,
        0x0700,
        0x0780,
        0x07C0,
        0x07E0,
        0x07F0,
        0x07E0,
        0x07C0,
        0x0780,
        0x0700,
        0x0600,
        0x0400,
        0x0000,
        0x0000,
    }
};

/* PAUSE */
static const ui_icon_t __attribute__((unused)) ui_icon_pause = {
    .row = {
        0x0000,
        0x0F3C,
        0x0F3C,
        0x0F3C,
        0x0F3C,
        0x0F3C,
        0x0F3C,
        0x0F3C,
        0x0F3C,
        0x0F3C,
        0x0F3C,
        0x0F3C,
        0x0000,
        0x0000,
        0x0000,
        0x0000,
    }
};

/* STOP */
static const ui_icon_t __attribute__((unused)) ui_icon_stop = {
    .row = {
        0x0000,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x3FFC,
        0x0000,
        0x0000,
        0x0000,
    }
};

/* SPK */
static const ui_icon_t __attribute__((unused)) ui_icon_spk = {
    .row = {
        0x0100,
        0x0300,
        0x0700,
        0x7FF8,
        0x7FF8,
        0x7FF8,
        0x7FF8,
        0x7FF8,
        0x7FF8,
        0x7FF8,
        0x0700,
        0x0300,
        0x0100,
        0x0000,
        0x0000,
        0x0000,
    }
};

/* BACK */
static const ui_icon_t __attribute__((unused)) ui_icon_back = {
    .row = {
        0x0000,
        0x0000,
        0x0080,
        0x0180,
        0x0380,
        0x0780,
        0x0F80,
        0x1F80,
        0x0F80,
        0x0780,
        0x0380,
        0x0180,
        0x0080,
        0x0000,
        0x0000,
        0x0000,
    }
};

/* UP */
static const ui_icon_t __attribute__((unused)) ui_icon_up = {
    .row = {
        0x0000,
        0x0180,
        0x03C0,
        0x07E0,
        0x0FF0,
        0x1FF8,
        0x0000,
        0x0000,
        0x0000,
        0x0180,
        0x03C0,
        0x07E0,
        0x0FF0,
        0x1FF8,
        0x0000,
        0x0000,
    }
};

/* DOWN */
static const ui_icon_t __attribute__((unused)) ui_icon_down = {
    .row = {
        0x0000,
        0x0000,
        0x1FF8,
        0x0FF0,
        0x07E0,
        0x03C0,
        0x0180,
        0x0000,
        0x0000,
        0x1FF8,
        0x0FF0,
        0x07E0,
        0x03C0,
        0x0180,
        0x0000,
        0x0000,
    }
};

/* REFRESH */
static const ui_icon_t __attribute__((unused)) ui_icon_refresh = {
    .row = {
        0x0000,
        0x0FE0,
        0x1010,
        0x2008,
        0x4004,
        0x4004,
        0x8002,
        0x8002,
        0x8002,
        0x8002,
        0x4004,
        0x401C,
        0x203C,
        0x1070,
        0x0FC0,
        0x0000,
    }
};

/* SD */
static const ui_icon_t __attribute__((unused)) ui_icon_sd = {
    .row = {
        0x0000,
        0x3FF8,
        0x2498,
        0x249C,
        0x2014,
        0x201E,
        0x2010,
        0x2010,
        0x2010,
        0x2010,
        0x2010,
        0x2010,
        0x2010,
        0x3FF0,
        0x0000,
        0x0000,
    }
};

/* ETH */
static const ui_icon_t __attribute__((unused)) ui_icon_eth = {
    .row = {
        0x0000,
        0x0000,
        0x3FFC,
        0x2004,
        0x2004,
        0x2554,
        0x2554,
        0x3FFC,
        0x0E70,
        0x0FF0,
        0x0FF0,
        0x0000,
        0x0000,
        0x0000,
        0x0000,
        0x0000,
    }
};

/* WARN */
static const ui_icon_t __attribute__((unused)) ui_icon_warn = {
    .row = {
        0x0000,
        0x0100,
        0x0100,
        0x0380,
        0x0380,
        0x06C0,
        0x06C0,
        0x06C0,
        0x0EE0,
        0x0C60,
        0x0C60,
        0x1C70,
        0x1FF0,
        0x0000,
        0x0000,
        0x0000,
    }
};

/* CHECK */
static const ui_icon_t __attribute__((unused)) ui_icon_check = {
    .row = {
        0x0000,
        0x0000,
        0x0000,
        0x001C,
        0x0038,
        0x0070,
        0x61C0,
        0x3380,
        0x1E00,
        0x1C00,
        0x0000,
        0x0000,
        0x0000,
        0x0000,
        0x0000,
        0x0000,
    }
};

/* HOME */
static const ui_icon_t __attribute__((unused)) ui_icon_home = {
    .row = {
        0x0000,
        0x0180,
        0x03C0,
        0x07E0,
        0x0FF0,
        0x1FF8,
        0x3FFC,
        0x381C,
        0x381C,
        0x399C,
        0x399C,
        0x399C,
        0x3FFC,
        0x0000,
        0x0000,
        0x0000,
    }
};

#ifdef __cplusplus
}
#endif

#endif /* CAMOS_UI_ICONS_H */
